name: midterm
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0


  lottie: ^2.3.2


  animated_text_kit: ^4.2.2

  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/images/diamond.png
    - assets/images/0-0.jfif
    - assets/images/1-0.jfif
    - assets/images/2-0.jfif
    - assets/images/3-0.jfif
    - assets/images/4-0.jfif
    - assets/images/5-0.jfif
    # TODO: Add slanted menu asset (104)
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg